In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv('train.csv')
df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         0
dtype: int64

In [2]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()

In [3]:
df['Sex'] = encoder.fit_transform(df['Sex'])
df['Embarked'] = encoder.fit_transform(df['Embarked'])

In [4]:
df.head(5)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name  Sex   Age  SibSp  Parch  \
0                            Braund, Mr. Owen Harris    1  22.0      1      0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...    0  38.0      1      0   
2                             Heikkinen, Miss. Laina    0  26.0      0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)    0  35.0      1      0   
4                           Allen, Mr. William Henry    1  35.0      0      0   

             Ticket     Fare Cabin  Embarked  
0         A/5 21171   7.2500   NaN         2  
1          PC 17599  71.2833   C85         0  
2  STON/O2. 3101282   7.9250   NaN         2  
3            113803  53.1000  C123         2  
4            373450   8.0500   NaN         2

In [5]:
df = df[['Survived','Pclass','Sex','SibSp','Parch','Embarked','Age']]
from sklearn.svm import LinearSVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix,accuracy_score
features = ['Survived','Pclass','Sex','SibSp','Parch','Embarked']
for i in features:
    x = df.drop(i,axis = 1)
    y = df[i]
    x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.2,random_state = 42)
    svc = LinearSVC(random_state= 0,max_iter=1000)
    svc.fit(x_train,y_train)
    y_pred = svc.predict(x_test)
    conf_matrix = confusion_matrix(y_pred,y_test)
    accuracy = accuracy_score(y_pred,y_test)
    print(i)
    print(conf_matrix)
    print('------------------------------------------------------------------------------------')

c:\users\pkkota\appdata\local\programs\python\python37\lib\site-packages\sklearn\svm\_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
c:\users\pkkota\appdata\local\programs\python\python37\lib\site-packages\sklearn\svm\_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
c:\users\pkkota\appdata\local\programs\python\python37\lib\site-packages\sklearn\svm\_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


Survived
[[91 18]
 [18 51]]
------------------------------------------------------------------------------------
Pclass
[[ 0  0  0]
 [ 0  0  0]
 [44 42 92]]
------------------------------------------------------------------------------------
Sex
[[62 76]
 [11 29]]
------------------------------------------------------------------------------------


c:\users\pkkota\appdata\local\programs\python\python37\lib\site-packages\sklearn\svm\_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
c:\users\pkkota\appdata\local\programs\python\python37\lib\site-packages\sklearn\svm\_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


SibSp
[[119  38   5   1   2   1   0]
 [  4   1   0   0   0   0   0]
 [  0   0   0   0   0   0   0]
 [  0   2   0   0   0   0   0]
 [  1   0   0   1   0   0   0]
 [  0   0   0   0   0   0   0]
 [  1   2   0   0   0   0   0]]
------------------------------------------------------------------------------------
Parch
[[131  25   7   1   2   0]
 [  0   3   0   0   0   0]
 [  1   2   5   0   0   0]
 [  0   0   0   0   0   0]
 [  0   0   0   0   0   0]
 [  1   0   0   0   0   0]]
------------------------------------------------------------------------------------
Embarked
[[ 16   3  20]
 [  0   2   4]
 [ 20   7 106]]
------------------------------------------------------------------------------------


c:\users\pkkota\appdata\local\programs\python\python37\lib\site-packages\sklearn\svm\_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
