In [7]:
import numpy as np
a = np.array([1,2,3])
print(a)
print(type(a))
print(a.ndim)

[1 2 3]
<class 'numpy.ndarray'>
1


Numpy Basics

In [10]:
a.ndim #Gives the number of access 
#Currently we create one dimension array so we are getting as 1

1

In [14]:
a.shape 
#Give the shape of the array which means the number of rows x n0.of cols
#if it is 1-D array we will get number of elements
#if it is 2-D array we will get no.of rows X no.of cols
#result we will get in the form of tuple

(3,)

In [16]:
a.size #no.of elements in an array either 1-D or 2-D or 3-D

3

In [19]:
a.dtype #Gives the datatype of the elements
#we can use either the default python data types or we can use the numpy datatypes
#such as numpy.int32, np.int64, np.float64

dtype('int32')

In [21]:
a.itemsize #returns the no. of bytes of each element in array

4

In [37]:
a.data.shape

(10,)

In [42]:
#creation of numpy array

##numpy arrange() will returns the 1-D array  equalent to range() in python

a = np.arange(10) 
a

#to create multiple rows and cols we use reshape() with arrange()
#in the below ex we are trying to reshape 20 elements 
#make sure those 20 elements fits after reshaping
#below ex: reshape(5,2) fits only 10 elements but we are trying to arrange 20
# make sure reshape() fits those 20 elements

#b = np.arange(20).reshape(5,2) 
#b

#so now we are arranging 20 elements in 4 rows 5 cols
c= np.arange(20).reshape(4,5)
c

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [45]:
#1-D Array
a1 = np.array([1,2,3,4])

#2-D Array creation
a12 = np.array([[1,2,3],[4,5,6]])
print(a12)

#To create complex array we can explicilty mention dtype = complex in np.array()
a2= np.array([[1,2,3],[4,5,6]], dtype=complex)
a2

[[1 2 3]
 [4 5 6]]


array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j]])

In [67]:
#Create a 2-D numpy array with default values as zero (0)
#Param we are giving is the shape of the matrix
z = np.zeros((4,5))
print(z)

#zeros_like() this method used to create a mat with the shape of other matrix

z1 = np.zeros_like(z)
print(z1)

o = np.ones((5,4))
print(o)

o1 = np.ones_like(o)
print(o1)

#By multiplying with a scalar we can create a mat with the same element
o2 = np.ones_like(o) *10
o2

#empty creates an array whose initial content is random depends on state of mem
r = np.empty((4,2))
r

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


array([[0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 3.06320700e-321],
       [7.53308506e-312, 7.53308506e-312]])

In [70]:
'''
arange is used with floating point arguments, 
it is generally not possible to predict the number of elements obtained, 
due to the finite floating point precision. For this reason,
it is usually better to use the function linspace
that receives as an argument the number of elements that we want
'''

#the below fn return 10 numbers between 0 to 1  
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [71]:
a3 = np.arange(24).reshape(2,3,4)
a3

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [2]:
#import sys
#np.set_printoptions(threshold=sys.maxsize)

#as we are trying to display multiple numbers we are seeing only 
#first and last details to see each and every element 
#we need to use set_printoutoptions(threshold= sys.maxsize)
#where sys is the system module which needs to be imported
import numpy as np
np.arange(10000).reshape(100,100)


array([[   0,    1,    2, ...,   97,   98,   99],
       [ 100,  101,  102, ...,  197,  198,  199],
       [ 200,  201,  202, ...,  297,  298,  299],
       ...,
       [9700, 9701, 9702, ..., 9797, 9798, 9799],
       [9800, 9801, 9802, ..., 9897, 9898, 9899],
       [9900, 9901, 9902, ..., 9997, 9998, 9999]])

# Basic Operations

In [3]:
#addition operation
a= np.array([1,2,3,4])
b = np.arange(4)
print(a)
print(b)

[1 2 3 4]
[0 1 2 3]


In [10]:
#addition
print(a+b)

#sub
print(a-b)

#check if every val is grater or lesser to specific val
a> 3

#multiplication
#Below is the normal multiplication which will multiply element wise only
print(a*b) 

#Normal matrix multiplication is achieved by using dot prod or @ operator
print(a@b)
print(a.dot(b))

#dot operator mul
a1= np.arange(4).reshape(2,2)
a2 = np.random.randint(100, size=4).reshape(2,2)

print(a1@a2)
print(a1.dot(a2))

[1 3 5 7]
[1 1 1 1]
[ 0  2  6 12]
20
20
[[ 47  20]
 [235 210]]
[[ 47  20]
 [235 210]]


In [16]:
import cv2
img = cv2.imread('Q1.jpg')

import sys
np.set_printoptions(threshold=sys.maxsize)
img.shape

#print(img)

(189, 319, 3)