# 1. Create a 3x3x3 array with random values 

In [1]:
import numpy as np
a = np.random.randint(100,size=27).reshape(3,3,3)
print(a)

[[[92 94 42]
  [61 28 96]
  [29 52 39]]

 [[28 38 40]
  [77 83 35]
  [93 78 34]]

 [[38 43 89]
  [14 54 70]
  [31 48 27]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [2]:
np.diagflat([[1,2], [3,4]],-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [3]:
patrn = np.zeros((8,8), dtype= int)
patrn[1::2, ::2]=1
patrn[::2, 1::2]=1
patrn


array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

# 4. Normalize a 5x5 random matrix

In [4]:
#Normalization of matrix 
randmat = np.random.randint(200,size=25).reshape(5,5)
xmax, xmin = randmat.max(), randmat.min()

normalized_mat = (randmat-xmin)/(xmax-xmin)
print(normalized_mat)


[[0.92592593 0.41798942 1.         0.60846561 0.        ]
 [0.18518519 0.96825397 0.52910053 0.23809524 0.71957672]
 [0.13227513 0.62433862 0.47089947 0.12169312 0.22222222]
 [0.21693122 0.66666667 0.52380952 0.71957672 0.97883598]
 [0.48148148 0.43915344 0.97883598 0.44444444 0.6031746 ]]


# 5.  How to find common values between two arrays?

In [5]:
a1 = np.random.randint(6,size=6).reshape(2,3)
a2 = np.random.randint(10,size=6).reshape(2,3)

print(a1)
print(a2)
np.intersect1d(a1,a2)

[[5 0 0]
 [5 5 2]]
[[0 8 7]
 [2 0 1]]


array([0, 2])

# 6.How to get the dates of yesterday, today and tomorrow?

In [6]:
yesterday = np.datetime64('Today') - np.timedelta64(1, 'D')
today = np.datetime64('Today') 
tomorrow = np.datetime64('Today') + np.timedelta64(1,'D')

print('Yesterday date', yesterday)
print('Today', today)
print('Tomorrow', tomorrow)

Yesterday date 2020-07-27
Today 2020-07-28
Tomorrow 2020-07-29


# 7. Consider two random array A and B, check if they are equal

In [7]:
arr1 = np.random.randint(1,size=4).reshape(2,2)
arr2 = np.random.randint(1,size=4).reshape(2,2)
print(arr1)
print(arr2)
print('Are both the random arrays are equal',np.array_equal(arr1,arr2))

arr1 = np.random.randint(4,size=4).reshape(2,2)
arr2 = np.random.randint(4,size=4).reshape(2,2)
print(arr1)
print(arr2)
print('Are both the random arrays are equal',np.array_equal(arr1,arr2))

[[0 0]
 [0 0]]
[[0 0]
 [0 0]]
Are both the random arrays are equal True
[[0 0]
 [2 3]]
[[3 1]
 [0 3]]
Are both the random arrays are equal False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [8]:
#Creation of 1-D numpy array itself is called a vector
vect = np.random.randint(200,size=10)
print(vect)
pos = np.argmax(vect)
print('Max val in the given vector', vect[pos])
vect[pos] = 0
print('Updated vector by replacing max number to zero as follows', vect)

[ 97  56  85  47  12  75  98  59 179 191]
Max val in the given vector 191
Updated vector by replacing max number to zero as follows [ 97  56  85  47  12  75  98  59 179   0]


# 9. How to print all the values of an array?

In [9]:
import sys
import numpy as np
ar = np.random.randint(10,size=4000).reshape(20,200)

#assuming to print all the values without missing in an array or matrix

np.set_printoptions(threshold=sys.maxsize)
print(ar)

[[5 6 1 8 0 1 9 4 5 8 8 0 4 2 2 3 2 4 5 1 6 6 8 7 3 6 0 6 8 2 5 9 8 9 3 7
  6 3 1 8 5 6 1 4 0 9 7 2 4 5 9 2 8 4 1 9 7 1 1 1 3 7 7 2 6 4 1 7 3 0 9 5
  2 2 9 8 8 8 7 7 6 6 4 6 9 5 3 0 8 5 6 2 6 4 1 6 8 8 1 6 3 0 4 6 5 2 0 0
  7 1 8 9 2 9 6 2 4 9 4 3 9 1 5 7 2 8 5 5 5 2 5 6 8 5 8 1 8 9 0 6 2 3 3 6
  2 1 2 1 2 7 1 9 6 7 5 0 6 8 9 9 9 5 2 0 9 9 3 8 4 5 9 2 6 9 0 4 4 2 2 7
  1 8 9 2 3 0 3 8 5 6 6 5 5 1 3 1 3 9 5 7]
 [1 0 1 9 7 3 9 7 8 2 9 3 7 9 4 0 1 1 1 9 4 3 9 9 7 2 8 8 4 3 3 1 4 8 8 7
  0 3 8 5 8 0 6 5 3 7 3 4 9 5 1 6 8 1 5 2 2 1 2 9 6 9 4 1 4 0 5 2 5 3 8 2
  8 4 4 2 1 1 8 6 3 5 7 0 3 5 0 6 8 0 2 3 7 2 9 6 2 3 8 2 3 6 1 1 8 8 1 2
  4 6 5 6 0 0 5 9 2 2 0 4 7 8 7 1 0 4 7 9 9 4 1 4 5 8 3 1 3 1 0 6 7 9 4 3
  2 4 6 7 3 9 3 5 3 6 7 1 2 0 7 6 7 7 1 5 2 7 0 9 3 9 7 1 0 9 5 4 8 9 1 7
  1 0 8 2 4 3 4 7 3 7 6 8 1 4 9 6 5 6 1 9]
 [7 8 3 4 3 8 4 4 6 9 4 4 4 6 4 1 5 1 2 0 0 9 9 9 6 6 9 8 3 2 4 3 4 4 5 6
  0 3 6 8 2 8 4 6 7 1 0 4 2 0 7 0 2 6 7 6 3 5 1 7 6 7 7 9 4 2 2 1 0 9 1 8
  8 5 4 6 2 6 7 6 1 8 0 6 

# 10.Subtract the mean of each row of a matrix

In [10]:
r = np.random.randint(20, size =12).reshape(3,4)
x = r.mean(axis=1, keepdims=True)
print(r)
print(x.shape)
res = r-x
res

[[13 15 17  4]
 [ 7  8 10 14]
 [ 6  4 17  5]]
(3, 1)


array([[ 0.75,  2.75,  4.75, -8.25],
       [-2.75, -1.75,  0.25,  4.25],
       [-2.  , -4.  ,  9.  , -3.  ]])

# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [11]:
a = np.random.randint(10,size=10)
print(a)
b = np.random.randint(0,len(a),20)
print(b)
np.add.at(a,b,1)
print(a)

[8 2 7 3 6 5 5 1 2 6]
[3 0 0 8 8 1 0 7 8 4 5 5 5 4 0 0 7 0 5 7]
[14  3  7  4  8  9  5  4  5  6]


# 12.How to get the diagonal of a dot product?

In [12]:
ar1 = np.random.randint(4,size=4).reshape(2,2)
ar2 = np.random.randint(4,size=4).reshape(2,2)
print(ar1)
print(ar2)
dot_mat = np.dot(ar1,ar2)
print('')
print('Dot prod mat \n',dot_mat)
print('Diagonal of dot product mat is ',np.diag(dot_mat))

[[2 0]
 [3 3]]
[[1 1]
 [0 0]]

Dot prod mat 
 [[2 2]
 [3 3]]
Diagonal of dot product mat is  [2 3]


# 13.How to find the most frequent value in an array?

In [13]:
arr = np.array([1,2,3,4,5,6,6,7,55,55,55,55,99,99,99])
np.bincount(arr).argmax()

55

# 14.How to get the n largest values of an array

In [14]:
ar0= np.arange(20)
print(ar0[np.argsort(ar0)[-4:]])
print(ar0)

[16 17 18 19]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


# 15.How to create a record array from a regular array?

In [15]:
a11 = np.array([100,101,102])
a12= np.array(['A','B','C'])
a13 = np.array([450,490,501])

rarr= np.core.records.fromarrays([a11,a12,a13],names='RollNo, Name, TotalMarks')
print(rarr.RollNo)
print(rarr.Name)
print(rarr.TotalMarks)

[100 101 102]
['A' 'B' 'C']
[450 490 501]
